_schema: _schema
paths:
  uploads:
  uploads_use_relative_path: true
  static: ''
collections_config:
  pages:
    path: content
    name: Pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  works:
    path: content/works
    name: Works
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Australia/Melbourne
markdown:
  engine: commonmark
  options:
    html: true
