_schema: _schema
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: content
    name: Pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: content/blog
    name: Blog
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Australia/Melbourne
markdown:
  engine: commonmark
  options:
    html: true
